name: Build Inspector Gadget container and push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'WebApp/**'

jobs:
  build-deploy-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build --no-cache --build-arg app_version=1.0.$GITHUB_RUN_NUMBER --build-arg source_version=$GITHUB_SHA -t channzaw/inspectorgadget:latest -f ./WebApp/Linux.Dockerfile ./WebApp
    - name: Push Docker Image to Registry
      run: docker push channzaw/inspectorgadget:latest
  build-deploy-windows:
    runs-on: windows-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build --no-cache --build-arg app_version=1.0.${env:GITHUB_RUN_NUMBER} --build-arg source_version=${env:GITHUB_SHA} -t channzaw/inspectorgadget:latest-windows -f ./WebApp/Windows.Dockerfile ./WebApp
    - name: Push Docker Image to Registry
      run: docker push jelledruyts/inspectorgadget:latest-windows
